import type { ProductColor } from "@/domain/product/product.types";

/** Palette de coloris partagée par le catalogue public et le back-office. */
export const COLORS = {
  ivoire: { id: "c-ivoire", name: "Ivoire", slug: "ivoire", family: "white", hex: "#F2EDE3" },
  blanc: { id: "c-blanc", name: "Blanc optique", slug: "blanc", family: "white", hex: "#FBFAF7" },
  beige: { id: "c-beige", name: "Beige sable", slug: "beige", family: "beige", hex: "#DCC7A6" },
  grege: { id: "c-grege", name: "Grège", slug: "grege", family: "beige", hex: "#C9BBA6" },
  gris: { id: "c-gris", name: "Gris perle", slug: "gris", family: "grey", hex: "#A5A5A2" },
  anthracite: {
    id: "c-anthracite",
    name: "Gris anthracite",
    slug: "anthracite",
    family: "grey",
    hex: "#4A4A48",
  },
  noir: { id: "c-noir", name: "Noir", slug: "noir", family: "black", hex: "#22211F" },
  camel: { id: "c-camel", name: "Camel", slug: "camel", family: "brown", hex: "#A9743F" },
  chocolat: {
    id: "c-chocolat",
    name: "Chocolat",
    slug: "chocolat",
    family: "brown",
    hex: "#5C3A24",
  },
  bordeaux: {
    id: "c-bordeaux",
    name: "Bordeaux",
    slug: "bordeaux",
    family: "red",
    hex: "#7B2230",
  },
  rose: { id: "c-rose", name: "Rose poudré", slug: "rose", family: "pink", hex: "#D9A3AB" },
  moutarde: {
    id: "c-moutarde",
    name: "Jaune moutarde",
    slug: "moutarde",
    family: "yellow",
    hex: "#C99A2E",
  },
  terracotta: {
    id: "c-terracotta",
    name: "Terracotta",
    slug: "terracotta",
    family: "orange",
    hex: "#B9633C",
  },
  vert: { id: "c-vert", name: "Vert olive", slug: "vert", family: "green", hex: "#5B6B45" },
  emeraude: {
    id: "c-emeraude",
    name: "Vert émeraude",
    slug: "emeraude",
    family: "green",
    hex: "#245A46",
  },
  bleu: { id: "c-bleu", name: "Bleu nuit", slug: "bleu", family: "blue", hex: "#2F4562" },
  bleuciel: {
    id: "c-bleuciel",
    name: "Bleu ciel",
    slug: "bleu-ciel",
    family: "blue",
    hex: "#8CA7C4",
  },
  prune: { id: "c-prune", name: "Prune", slug: "prune", family: "purple", hex: "#5F3E63" },
  dore: { id: "c-dore", name: "Doré", slug: "dore", family: "metallic", hex: "#B99B63" },
  argent: { id: "c-argent", name: "Argent", slug: "argent", family: "metallic", hex: "#C9CBCC" },
  bois: {
    id: "c-bois",
    name: "Bois naturel",
    slug: "bois-naturel",
    family: "brown",
    hex: "#B08B57",
  },
} satisfies Record<string, ProductColor>;
