/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EmbrassesRouteImport } from './routes/embrasses'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as GuideDesMesuresRouteImport } from './routes/guide-des-mesures'
import { Route as InspirationsRouteImport } from './routes/inspirations'
import { Route as LivraisonEtRetoursRouteImport } from './routes/livraison-et-retours'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as NouveautesRouteImport } from './routes/nouveautes'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ProfessionnelsRouteImport } from './routes/professionnels'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as SuiviCommandeRouteImport } from './routes/suivi-commande'
import { Route as SurMesureRouteImport } from './routes/sur-mesure'
import { Route as TringlesRouteImport } from './routes/tringles'
import { Route as AccessoiresIndexRouteImport } from './routes/accessoires.index'
import { Route as AccessoiresEmbrassesRouteImport } from './routes/accessoires.embrasses'
import { Route as AccessoiresPetitesPiecesRouteImport } from './routes/accessoires.petites-pieces'
import { Route as AccessoiresRailsRouteImport } from './routes/accessoires.rails'
import { Route as AccessoiresTringlesRouteImport } from './routes/accessoires.tringles'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CommandeIndexRouteImport } from './routes/commande.index'
import { Route as CommandeConfirmationRouteImport } from './routes/commande.confirmation'
import { Route as CoussinsIndexRouteImport } from './routes/coussins.index'
import { Route as CoussinsLinRouteImport } from './routes/coussins.lin'
import { Route as CoussinsLotsRouteImport } from './routes/coussins.lots'
import { Route as CoussinsVeloursRouteImport } from './routes/coussins.velours'
import { Route as GalettesDeChaiseIndexRouteImport } from './routes/galettes-de-chaise.index'
import { Route as GalettesDeChaiseCarreesRouteImport } from './routes/galettes-de-chaise.carrees'
import { Route as GalettesDeChaiseRondesRouteImport } from './routes/galettes-de-chaise.rondes'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as RideauxIndexRouteImport } from './routes/rideaux.index'
import { Route as RideauxLinRouteImport } from './routes/rideaux.lin'
import { Route as RideauxOccultantsRouteImport } from './routes/rideaux.occultants'
import { Route as RideauxOeilletsRouteImport } from './routes/rideaux.oeillets'
import { Route as RideauxPacksRouteImport } from './routes/rideaux.packs'
import { Route as RideauxRailRouteImport } from './routes/rideaux.rail'
import { Route as RideauxSatinRouteImport } from './routes/rideaux.satin'
import { Route as RideauxTamisantsRouteImport } from './routes/rideaux.tamisants'
import { Route as RideauxThermiquesRouteImport } from './routes/rideaux.thermiques'
import { Route as RideauxVeloursRouteImport } from './routes/rideaux.velours'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresBambouRouteImport } from './routes/stores.bambou'
import { Route as StoresEnrouleursRouteImport } from './routes/stores.enrouleurs'
import { Route as StoresJourNuitRouteImport } from './routes/stores.jour-nuit'
import { Route as StoresOccultantsRouteImport } from './routes/stores.occultants'
import { Route as StoresSansPercageRouteImport } from './routes/stores.sans-percage'
import { Route as VoilagesIndexRouteImport } from './routes/voilages.index'
import { Route as VoilagesGrandeLargeurRouteImport } from './routes/voilages.grande-largeur'
import { Route as VoilagesMotifsRouteImport } from './routes/voilages.motifs'
import { Route as VoilagesRailRouteImport } from './routes/voilages.rail'
import { Route as VoilagesUnisRouteImport } from './routes/voilages.unis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbrassesRoute = EmbrassesRouteImport.update({
  id: '/embrasses',
  path: '/embrasses',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideDesMesuresRoute = GuideDesMesuresRouteImport.update({
  id: '/guide-des-mesures',
  path: '/guide-des-mesures',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationsRoute = InspirationsRouteImport.update({
  id: '/inspirations',
  path: '/inspirations',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonEtRetoursRoute = LivraisonEtRetoursRouteImport.update({
  id: '/livraison-et-retours',
  path: '/livraison-et-retours',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveautesRoute = NouveautesRouteImport.update({
  id: '/nouveautes',
  path: '/nouveautes',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionnelsRoute = ProfessionnelsRouteImport.update({
  id: '/professionnels',
  path: '/professionnels',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviCommandeRoute = SuiviCommandeRouteImport.update({
  id: '/suivi-commande',
  path: '/suivi-commande',
  getParentRoute: () => rootRouteImport,
} as any)
const SurMesureRoute = SurMesureRouteImport.update({
  id: '/sur-mesure',
  path: '/sur-mesure',
  getParentRoute: () => rootRouteImport,
} as any)
const TringlesRoute = TringlesRouteImport.update({
  id: '/tringles',
  path: '/tringles',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoiresIndexRoute = AccessoiresIndexRouteImport.update({
  id: '/accessoires/',
  path: '/accessoires/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoiresEmbrassesRoute = AccessoiresEmbrassesRouteImport.update({
  id: '/accessoires/embrasses',
  path: '/accessoires/embrasses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoiresPetitesPiecesRoute =
  AccessoiresPetitesPiecesRouteImport.update({
    id: '/accessoires/petites-pieces',
    path: '/accessoires/petites-pieces',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccessoiresRailsRoute = AccessoiresRailsRouteImport.update({
  id: '/accessoires/rails',
  path: '/accessoires/rails',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoiresTringlesRoute = AccessoiresTringlesRouteImport.update({
  id: '/accessoires/tringles',
  path: '/accessoires/tringles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CommandeIndexRoute = CommandeIndexRouteImport.update({
  id: '/commande/',
  path: '/commande/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeConfirmationRoute = CommandeConfirmationRouteImport.update({
  id: '/commande/confirmation',
  path: '/commande/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CoussinsIndexRoute = CoussinsIndexRouteImport.update({
  id: '/coussins/',
  path: '/coussins/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoussinsLinRoute = CoussinsLinRouteImport.update({
  id: '/coussins/lin',
  path: '/coussins/lin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoussinsLotsRoute = CoussinsLotsRouteImport.update({
  id: '/coussins/lots',
  path: '/coussins/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const CoussinsVeloursRoute = CoussinsVeloursRouteImport.update({
  id: '/coussins/velours',
  path: '/coussins/velours',
  getParentRoute: () => rootRouteImport,
} as any)
const GalettesDeChaiseIndexRoute = GalettesDeChaiseIndexRouteImport.update({
  id: '/galettes-de-chaise/',
  path: '/galettes-de-chaise/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalettesDeChaiseCarreesRoute = GalettesDeChaiseCarreesRouteImport.update({
  id: '/galettes-de-chaise/carrees',
  path: '/galettes-de-chaise/carrees',
  getParentRoute: () => rootRouteImport,
} as any)
const GalettesDeChaiseRondesRoute = GalettesDeChaiseRondesRouteImport.update({
  id: '/galettes-de-chaise/rondes',
  path: '/galettes-de-chaise/rondes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxIndexRoute = RideauxIndexRouteImport.update({
  id: '/rideaux/',
  path: '/rideaux/',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxLinRoute = RideauxLinRouteImport.update({
  id: '/rideaux/lin',
  path: '/rideaux/lin',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxOccultantsRoute = RideauxOccultantsRouteImport.update({
  id: '/rideaux/occultants',
  path: '/rideaux/occultants',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxOeilletsRoute = RideauxOeilletsRouteImport.update({
  id: '/rideaux/oeillets',
  path: '/rideaux/oeillets',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxPacksRoute = RideauxPacksRouteImport.update({
  id: '/rideaux/packs',
  path: '/rideaux/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxRailRoute = RideauxRailRouteImport.update({
  id: '/rideaux/rail',
  path: '/rideaux/rail',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxSatinRoute = RideauxSatinRouteImport.update({
  id: '/rideaux/satin',
  path: '/rideaux/satin',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxTamisantsRoute = RideauxTamisantsRouteImport.update({
  id: '/rideaux/tamisants',
  path: '/rideaux/tamisants',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxThermiquesRoute = RideauxThermiquesRouteImport.update({
  id: '/rideaux/thermiques',
  path: '/rideaux/thermiques',
  getParentRoute: () => rootRouteImport,
} as any)
const RideauxVeloursRoute = RideauxVeloursRouteImport.update({
  id: '/rideaux/velours',
  path: '/rideaux/velours',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresBambouRoute = StoresBambouRouteImport.update({
  id: '/stores/bambou',
  path: '/stores/bambou',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresEnrouleursRoute = StoresEnrouleursRouteImport.update({
  id: '/stores/enrouleurs',
  path: '/stores/enrouleurs',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresJourNuitRoute = StoresJourNuitRouteImport.update({
  id: '/stores/jour-nuit',
  path: '/stores/jour-nuit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresOccultantsRoute = StoresOccultantsRouteImport.update({
  id: '/stores/occultants',
  path: '/stores/occultants',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresSansPercageRoute = StoresSansPercageRouteImport.update({
  id: '/stores/sans-percage',
  path: '/stores/sans-percage',
  getParentRoute: () => rootRouteImport,
} as any)
const VoilagesIndexRoute = VoilagesIndexRouteImport.update({
  id: '/voilages/',
  path: '/voilages/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoilagesGrandeLargeurRoute = VoilagesGrandeLargeurRouteImport.update({
  id: '/voilages/grande-largeur',
  path: '/voilages/grande-largeur',
  getParentRoute: () => rootRouteImport,
} as any)
const VoilagesMotifsRoute = VoilagesMotifsRouteImport.update({
  id: '/voilages/motifs',
  path: '/voilages/motifs',
  getParentRoute: () => rootRouteImport,
} as any)
const VoilagesRailRoute = VoilagesRailRouteImport.update({
  id: '/voilages/rail',
  path: '/voilages/rail',
  getParentRoute: () => rootRouteImport,
} as any)
const VoilagesUnisRoute = VoilagesUnisRouteImport.update({
  id: '/voilages/unis',
  path: '/voilages/unis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/embrasses': typeof EmbrassesRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/guide-des-mesures': typeof GuideDesMesuresRoute
  '/inspirations': typeof InspirationsRoute
  '/livraison-et-retours': typeof LivraisonEtRetoursRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nouveautes': typeof NouveautesRoute
  '/panier': typeof PanierRoute
  '/professionnels': typeof ProfessionnelsRoute
  '/promotions': typeof PromotionsRoute
  '/recherche': typeof RechercheRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/sur-mesure': typeof SurMesureRoute
  '/tringles': typeof TringlesRoute
  '/accessoires/embrasses': typeof AccessoiresEmbrassesRoute
  '/accessoires/petites-pieces': typeof AccessoiresPetitesPiecesRoute
  '/accessoires/rails': typeof AccessoiresRailsRoute
  '/accessoires/tringles': typeof AccessoiresTringlesRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/coussins/lin': typeof CoussinsLinRoute
  '/coussins/lots': typeof CoussinsLotsRoute
  '/coussins/velours': typeof CoussinsVeloursRoute
  '/galettes-de-chaise/carrees': typeof GalettesDeChaiseCarreesRoute
  '/galettes-de-chaise/rondes': typeof GalettesDeChaiseRondesRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/rideaux/lin': typeof RideauxLinRoute
  '/rideaux/occultants': typeof RideauxOccultantsRoute
  '/rideaux/oeillets': typeof RideauxOeilletsRoute
  '/rideaux/packs': typeof RideauxPacksRoute
  '/rideaux/rail': typeof RideauxRailRoute
  '/rideaux/satin': typeof RideauxSatinRoute
  '/rideaux/tamisants': typeof RideauxTamisantsRoute
  '/rideaux/thermiques': typeof RideauxThermiquesRoute
  '/rideaux/velours': typeof RideauxVeloursRoute
  '/stores/bambou': typeof StoresBambouRoute
  '/stores/enrouleurs': typeof StoresEnrouleursRoute
  '/stores/jour-nuit': typeof StoresJourNuitRoute
  '/stores/occultants': typeof StoresOccultantsRoute
  '/stores/sans-percage': typeof StoresSansPercageRoute
  '/voilages/grande-largeur': typeof VoilagesGrandeLargeurRoute
  '/voilages/motifs': typeof VoilagesMotifsRoute
  '/voilages/rail': typeof VoilagesRailRoute
  '/voilages/unis': typeof VoilagesUnisRoute
  '/accessoires/': typeof AccessoiresIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/commande/': typeof CommandeIndexRoute
  '/coussins/': typeof CoussinsIndexRoute
  '/galettes-de-chaise/': typeof GalettesDeChaiseIndexRoute
  '/rideaux/': typeof RideauxIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/voilages/': typeof VoilagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/embrasses': typeof EmbrassesRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/guide-des-mesures': typeof GuideDesMesuresRoute
  '/inspirations': typeof InspirationsRoute
  '/livraison-et-retours': typeof LivraisonEtRetoursRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nouveautes': typeof NouveautesRoute
  '/panier': typeof PanierRoute
  '/professionnels': typeof ProfessionnelsRoute
  '/promotions': typeof PromotionsRoute
  '/recherche': typeof RechercheRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/sur-mesure': typeof SurMesureRoute
  '/tringles': typeof TringlesRoute
  '/accessoires/embrasses': typeof AccessoiresEmbrassesRoute
  '/accessoires/petites-pieces': typeof AccessoiresPetitesPiecesRoute
  '/accessoires/rails': typeof AccessoiresRailsRoute
  '/accessoires/tringles': typeof AccessoiresTringlesRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/coussins/lin': typeof CoussinsLinRoute
  '/coussins/lots': typeof CoussinsLotsRoute
  '/coussins/velours': typeof CoussinsVeloursRoute
  '/galettes-de-chaise/carrees': typeof GalettesDeChaiseCarreesRoute
  '/galettes-de-chaise/rondes': typeof GalettesDeChaiseRondesRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/rideaux/lin': typeof RideauxLinRoute
  '/rideaux/occultants': typeof RideauxOccultantsRoute
  '/rideaux/oeillets': typeof RideauxOeilletsRoute
  '/rideaux/packs': typeof RideauxPacksRoute
  '/rideaux/rail': typeof RideauxRailRoute
  '/rideaux/satin': typeof RideauxSatinRoute
  '/rideaux/tamisants': typeof RideauxTamisantsRoute
  '/rideaux/thermiques': typeof RideauxThermiquesRoute
  '/rideaux/velours': typeof RideauxVeloursRoute
  '/stores/bambou': typeof StoresBambouRoute
  '/stores/enrouleurs': typeof StoresEnrouleursRoute
  '/stores/jour-nuit': typeof StoresJourNuitRoute
  '/stores/occultants': typeof StoresOccultantsRoute
  '/stores/sans-percage': typeof StoresSansPercageRoute
  '/voilages/grande-largeur': typeof VoilagesGrandeLargeurRoute
  '/voilages/motifs': typeof VoilagesMotifsRoute
  '/voilages/rail': typeof VoilagesRailRoute
  '/voilages/unis': typeof VoilagesUnisRoute
  '/accessoires': typeof AccessoiresIndexRoute
  '/admin': typeof AdminIndexRoute
  '/commande': typeof CommandeIndexRoute
  '/coussins': typeof CoussinsIndexRoute
  '/galettes-de-chaise': typeof GalettesDeChaiseIndexRoute
  '/rideaux': typeof RideauxIndexRoute
  '/stores': typeof StoresIndexRoute
  '/voilages': typeof VoilagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/embrasses': typeof EmbrassesRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/guide-des-mesures': typeof GuideDesMesuresRoute
  '/inspirations': typeof InspirationsRoute
  '/livraison-et-retours': typeof LivraisonEtRetoursRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nouveautes': typeof NouveautesRoute
  '/panier': typeof PanierRoute
  '/professionnels': typeof ProfessionnelsRoute
  '/promotions': typeof PromotionsRoute
  '/recherche': typeof RechercheRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/sur-mesure': typeof SurMesureRoute
  '/tringles': typeof TringlesRoute
  '/accessoires/embrasses': typeof AccessoiresEmbrassesRoute
  '/accessoires/petites-pieces': typeof AccessoiresPetitesPiecesRoute
  '/accessoires/rails': typeof AccessoiresRailsRoute
  '/accessoires/tringles': typeof AccessoiresTringlesRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/coussins/lin': typeof CoussinsLinRoute
  '/coussins/lots': typeof CoussinsLotsRoute
  '/coussins/velours': typeof CoussinsVeloursRoute
  '/galettes-de-chaise/carrees': typeof GalettesDeChaiseCarreesRoute
  '/galettes-de-chaise/rondes': typeof GalettesDeChaiseRondesRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/rideaux/lin': typeof RideauxLinRoute
  '/rideaux/occultants': typeof RideauxOccultantsRoute
  '/rideaux/oeillets': typeof RideauxOeilletsRoute
  '/rideaux/packs': typeof RideauxPacksRoute
  '/rideaux/rail': typeof RideauxRailRoute
  '/rideaux/satin': typeof RideauxSatinRoute
  '/rideaux/tamisants': typeof RideauxTamisantsRoute
  '/rideaux/thermiques': typeof RideauxThermiquesRoute
  '/rideaux/velours': typeof RideauxVeloursRoute
  '/stores/bambou': typeof StoresBambouRoute
  '/stores/enrouleurs': typeof StoresEnrouleursRoute
  '/stores/jour-nuit': typeof StoresJourNuitRoute
  '/stores/occultants': typeof StoresOccultantsRoute
  '/stores/sans-percage': typeof StoresSansPercageRoute
  '/voilages/grande-largeur': typeof VoilagesGrandeLargeurRoute
  '/voilages/motifs': typeof VoilagesMotifsRoute
  '/voilages/rail': typeof VoilagesRailRoute
  '/voilages/unis': typeof VoilagesUnisRoute
  '/accessoires/': typeof AccessoiresIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/commande/': typeof CommandeIndexRoute
  '/coussins/': typeof CoussinsIndexRoute
  '/galettes-de-chaise/': typeof GalettesDeChaiseIndexRoute
  '/rideaux/': typeof RideauxIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/voilages/': typeof VoilagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/a-propos'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/embrasses'
    | '/faq'
    | '/favoris'
    | '/guide-des-mesures'
    | '/inspirations'
    | '/livraison-et-retours'
    | '/mentions-legales'
    | '/nouveautes'
    | '/panier'
    | '/professionnels'
    | '/promotions'
    | '/recherche'
    | '/suivi-commande'
    | '/sur-mesure'
    | '/tringles'
    | '/accessoires/embrasses'
    | '/accessoires/petites-pieces'
    | '/accessoires/rails'
    | '/accessoires/tringles'
    | '/commande/confirmation'
    | '/coussins/lin'
    | '/coussins/lots'
    | '/coussins/velours'
    | '/galettes-de-chaise/carrees'
    | '/galettes-de-chaise/rondes'
    | '/produit/$slug'
    | '/rideaux/lin'
    | '/rideaux/occultants'
    | '/rideaux/oeillets'
    | '/rideaux/packs'
    | '/rideaux/rail'
    | '/rideaux/satin'
    | '/rideaux/tamisants'
    | '/rideaux/thermiques'
    | '/rideaux/velours'
    | '/stores/bambou'
    | '/stores/enrouleurs'
    | '/stores/jour-nuit'
    | '/stores/occultants'
    | '/stores/sans-percage'
    | '/voilages/grande-largeur'
    | '/voilages/motifs'
    | '/voilages/rail'
    | '/voilages/unis'
    | '/accessoires/'
    | '/admin/'
    | '/commande/'
    | '/coussins/'
    | '/galettes-de-chaise/'
    | '/rideaux/'
    | '/stores/'
    | '/voilages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/embrasses'
    | '/faq'
    | '/favoris'
    | '/guide-des-mesures'
    | '/inspirations'
    | '/livraison-et-retours'
    | '/mentions-legales'
    | '/nouveautes'
    | '/panier'
    | '/professionnels'
    | '/promotions'
    | '/recherche'
    | '/suivi-commande'
    | '/sur-mesure'
    | '/tringles'
    | '/accessoires/embrasses'
    | '/accessoires/petites-pieces'
    | '/accessoires/rails'
    | '/accessoires/tringles'
    | '/commande/confirmation'
    | '/coussins/lin'
    | '/coussins/lots'
    | '/coussins/velours'
    | '/galettes-de-chaise/carrees'
    | '/galettes-de-chaise/rondes'
    | '/produit/$slug'
    | '/rideaux/lin'
    | '/rideaux/occultants'
    | '/rideaux/oeillets'
    | '/rideaux/packs'
    | '/rideaux/rail'
    | '/rideaux/satin'
    | '/rideaux/tamisants'
    | '/rideaux/thermiques'
    | '/rideaux/velours'
    | '/stores/bambou'
    | '/stores/enrouleurs'
    | '/stores/jour-nuit'
    | '/stores/occultants'
    | '/stores/sans-percage'
    | '/voilages/grande-largeur'
    | '/voilages/motifs'
    | '/voilages/rail'
    | '/voilages/unis'
    | '/accessoires'
    | '/admin'
    | '/commande'
    | '/coussins'
    | '/galettes-de-chaise'
    | '/rideaux'
    | '/stores'
    | '/voilages'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/a-propos'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/embrasses'
    | '/faq'
    | '/favoris'
    | '/guide-des-mesures'
    | '/inspirations'
    | '/livraison-et-retours'
    | '/mentions-legales'
    | '/nouveautes'
    | '/panier'
    | '/professionnels'
    | '/promotions'
    | '/recherche'
    | '/suivi-commande'
    | '/sur-mesure'
    | '/tringles'
    | '/accessoires/embrasses'
    | '/accessoires/petites-pieces'
    | '/accessoires/rails'
    | '/accessoires/tringles'
    | '/commande/confirmation'
    | '/coussins/lin'
    | '/coussins/lots'
    | '/coussins/velours'
    | '/galettes-de-chaise/carrees'
    | '/galettes-de-chaise/rondes'
    | '/produit/$slug'
    | '/rideaux/lin'
    | '/rideaux/occultants'
    | '/rideaux/oeillets'
    | '/rideaux/packs'
    | '/rideaux/rail'
    | '/rideaux/satin'
    | '/rideaux/tamisants'
    | '/rideaux/thermiques'
    | '/rideaux/velours'
    | '/stores/bambou'
    | '/stores/enrouleurs'
    | '/stores/jour-nuit'
    | '/stores/occultants'
    | '/stores/sans-percage'
    | '/voilages/grande-largeur'
    | '/voilages/motifs'
    | '/voilages/rail'
    | '/voilages/unis'
    | '/accessoires/'
    | '/admin/'
    | '/commande/'
    | '/coussins/'
    | '/galettes-de-chaise/'
    | '/rideaux/'
    | '/stores/'
    | '/voilages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  EmbrassesRoute: typeof EmbrassesRoute
  FaqRoute: typeof FaqRoute
  FavorisRoute: typeof FavorisRoute
  GuideDesMesuresRoute: typeof GuideDesMesuresRoute
  InspirationsRoute: typeof InspirationsRoute
  LivraisonEtRetoursRoute: typeof LivraisonEtRetoursRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  NouveautesRoute: typeof NouveautesRoute
  PanierRoute: typeof PanierRoute
  ProfessionnelsRoute: typeof ProfessionnelsRoute
  PromotionsRoute: typeof PromotionsRoute
  RechercheRoute: typeof RechercheRoute
  SuiviCommandeRoute: typeof SuiviCommandeRoute
  SurMesureRoute: typeof SurMesureRoute
  TringlesRoute: typeof TringlesRoute
  AccessoiresEmbrassesRoute: typeof AccessoiresEmbrassesRoute
  AccessoiresPetitesPiecesRoute: typeof AccessoiresPetitesPiecesRoute
  AccessoiresRailsRoute: typeof AccessoiresRailsRoute
  AccessoiresTringlesRoute: typeof AccessoiresTringlesRoute
  CommandeConfirmationRoute: typeof CommandeConfirmationRoute
  CoussinsLinRoute: typeof CoussinsLinRoute
  CoussinsLotsRoute: typeof CoussinsLotsRoute
  CoussinsVeloursRoute: typeof CoussinsVeloursRoute
  GalettesDeChaiseCarreesRoute: typeof GalettesDeChaiseCarreesRoute
  GalettesDeChaiseRondesRoute: typeof GalettesDeChaiseRondesRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  RideauxLinRoute: typeof RideauxLinRoute
  RideauxOccultantsRoute: typeof RideauxOccultantsRoute
  RideauxOeilletsRoute: typeof RideauxOeilletsRoute
  RideauxPacksRoute: typeof RideauxPacksRoute
  RideauxRailRoute: typeof RideauxRailRoute
  RideauxSatinRoute: typeof RideauxSatinRoute
  RideauxTamisantsRoute: typeof RideauxTamisantsRoute
  RideauxThermiquesRoute: typeof RideauxThermiquesRoute
  RideauxVeloursRoute: typeof RideauxVeloursRoute
  StoresBambouRoute: typeof StoresBambouRoute
  StoresEnrouleursRoute: typeof StoresEnrouleursRoute
  StoresJourNuitRoute: typeof StoresJourNuitRoute
  StoresOccultantsRoute: typeof StoresOccultantsRoute
  StoresSansPercageRoute: typeof StoresSansPercageRoute
  VoilagesGrandeLargeurRoute: typeof VoilagesGrandeLargeurRoute
  VoilagesMotifsRoute: typeof VoilagesMotifsRoute
  VoilagesRailRoute: typeof VoilagesRailRoute
  VoilagesUnisRoute: typeof VoilagesUnisRoute
  AccessoiresIndexRoute: typeof AccessoiresIndexRoute
  CommandeIndexRoute: typeof CommandeIndexRoute
  CoussinsIndexRoute: typeof CoussinsIndexRoute
  GalettesDeChaiseIndexRoute: typeof GalettesDeChaiseIndexRoute
  RideauxIndexRoute: typeof RideauxIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  VoilagesIndexRoute: typeof VoilagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embrasses': {
      id: '/embrasses'
      path: '/embrasses'
      fullPath: '/embrasses'
      preLoaderRoute: typeof EmbrassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-des-mesures': {
      id: '/guide-des-mesures'
      path: '/guide-des-mesures'
      fullPath: '/guide-des-mesures'
      preLoaderRoute: typeof GuideDesMesuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirations': {
      id: '/inspirations'
      path: '/inspirations'
      fullPath: '/inspirations'
      preLoaderRoute: typeof InspirationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison-et-retours': {
      id: '/livraison-et-retours'
      path: '/livraison-et-retours'
      fullPath: '/livraison-et-retours'
      preLoaderRoute: typeof LivraisonEtRetoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveautes': {
      id: '/nouveautes'
      path: '/nouveautes'
      fullPath: '/nouveautes'
      preLoaderRoute: typeof NouveautesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionnels': {
      id: '/professionnels'
      path: '/professionnels'
      fullPath: '/professionnels'
      preLoaderRoute: typeof ProfessionnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi-commande': {
      id: '/suivi-commande'
      path: '/suivi-commande'
      fullPath: '/suivi-commande'
      preLoaderRoute: typeof SuiviCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sur-mesure': {
      id: '/sur-mesure'
      path: '/sur-mesure'
      fullPath: '/sur-mesure'
      preLoaderRoute: typeof SurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tringles': {
      id: '/tringles'
      path: '/tringles'
      fullPath: '/tringles'
      preLoaderRoute: typeof TringlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessoires/': {
      id: '/accessoires/'
      path: '/accessoires'
      fullPath: '/accessoires/'
      preLoaderRoute: typeof AccessoiresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessoires/embrasses': {
      id: '/accessoires/embrasses'
      path: '/accessoires/embrasses'
      fullPath: '/accessoires/embrasses'
      preLoaderRoute: typeof AccessoiresEmbrassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessoires/petites-pieces': {
      id: '/accessoires/petites-pieces'
      path: '/accessoires/petites-pieces'
      fullPath: '/accessoires/petites-pieces'
      preLoaderRoute: typeof AccessoiresPetitesPiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessoires/rails': {
      id: '/accessoires/rails'
      path: '/accessoires/rails'
      fullPath: '/accessoires/rails'
      preLoaderRoute: typeof AccessoiresRailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessoires/tringles': {
      id: '/accessoires/tringles'
      path: '/accessoires/tringles'
      fullPath: '/accessoires/tringles'
      preLoaderRoute: typeof AccessoiresTringlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/commande/': {
      id: '/commande/'
      path: '/commande'
      fullPath: '/commande/'
      preLoaderRoute: typeof CommandeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/confirmation': {
      id: '/commande/confirmation'
      path: '/commande/confirmation'
      fullPath: '/commande/confirmation'
      preLoaderRoute: typeof CommandeConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coussins/': {
      id: '/coussins/'
      path: '/coussins'
      fullPath: '/coussins/'
      preLoaderRoute: typeof CoussinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coussins/lin': {
      id: '/coussins/lin'
      path: '/coussins/lin'
      fullPath: '/coussins/lin'
      preLoaderRoute: typeof CoussinsLinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coussins/lots': {
      id: '/coussins/lots'
      path: '/coussins/lots'
      fullPath: '/coussins/lots'
      preLoaderRoute: typeof CoussinsLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coussins/velours': {
      id: '/coussins/velours'
      path: '/coussins/velours'
      fullPath: '/coussins/velours'
      preLoaderRoute: typeof CoussinsVeloursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galettes-de-chaise/': {
      id: '/galettes-de-chaise/'
      path: '/galettes-de-chaise'
      fullPath: '/galettes-de-chaise/'
      preLoaderRoute: typeof GalettesDeChaiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galettes-de-chaise/carrees': {
      id: '/galettes-de-chaise/carrees'
      path: '/galettes-de-chaise/carrees'
      fullPath: '/galettes-de-chaise/carrees'
      preLoaderRoute: typeof GalettesDeChaiseCarreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galettes-de-chaise/rondes': {
      id: '/galettes-de-chaise/rondes'
      path: '/galettes-de-chaise/rondes'
      fullPath: '/galettes-de-chaise/rondes'
      preLoaderRoute: typeof GalettesDeChaiseRondesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/': {
      id: '/rideaux/'
      path: '/rideaux'
      fullPath: '/rideaux/'
      preLoaderRoute: typeof RideauxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/lin': {
      id: '/rideaux/lin'
      path: '/rideaux/lin'
      fullPath: '/rideaux/lin'
      preLoaderRoute: typeof RideauxLinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/occultants': {
      id: '/rideaux/occultants'
      path: '/rideaux/occultants'
      fullPath: '/rideaux/occultants'
      preLoaderRoute: typeof RideauxOccultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/oeillets': {
      id: '/rideaux/oeillets'
      path: '/rideaux/oeillets'
      fullPath: '/rideaux/oeillets'
      preLoaderRoute: typeof RideauxOeilletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/packs': {
      id: '/rideaux/packs'
      path: '/rideaux/packs'
      fullPath: '/rideaux/packs'
      preLoaderRoute: typeof RideauxPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/rail': {
      id: '/rideaux/rail'
      path: '/rideaux/rail'
      fullPath: '/rideaux/rail'
      preLoaderRoute: typeof RideauxRailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/satin': {
      id: '/rideaux/satin'
      path: '/rideaux/satin'
      fullPath: '/rideaux/satin'
      preLoaderRoute: typeof RideauxSatinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/tamisants': {
      id: '/rideaux/tamisants'
      path: '/rideaux/tamisants'
      fullPath: '/rideaux/tamisants'
      preLoaderRoute: typeof RideauxTamisantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/thermiques': {
      id: '/rideaux/thermiques'
      path: '/rideaux/thermiques'
      fullPath: '/rideaux/thermiques'
      preLoaderRoute: typeof RideauxThermiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rideaux/velours': {
      id: '/rideaux/velours'
      path: '/rideaux/velours'
      fullPath: '/rideaux/velours'
      preLoaderRoute: typeof RideauxVeloursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/bambou': {
      id: '/stores/bambou'
      path: '/stores/bambou'
      fullPath: '/stores/bambou'
      preLoaderRoute: typeof StoresBambouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/enrouleurs': {
      id: '/stores/enrouleurs'
      path: '/stores/enrouleurs'
      fullPath: '/stores/enrouleurs'
      preLoaderRoute: typeof StoresEnrouleursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/jour-nuit': {
      id: '/stores/jour-nuit'
      path: '/stores/jour-nuit'
      fullPath: '/stores/jour-nuit'
      preLoaderRoute: typeof StoresJourNuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/occultants': {
      id: '/stores/occultants'
      path: '/stores/occultants'
      fullPath: '/stores/occultants'
      preLoaderRoute: typeof StoresOccultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/sans-percage': {
      id: '/stores/sans-percage'
      path: '/stores/sans-percage'
      fullPath: '/stores/sans-percage'
      preLoaderRoute: typeof StoresSansPercageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voilages/': {
      id: '/voilages/'
      path: '/voilages'
      fullPath: '/voilages/'
      preLoaderRoute: typeof VoilagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voilages/grande-largeur': {
      id: '/voilages/grande-largeur'
      path: '/voilages/grande-largeur'
      fullPath: '/voilages/grande-largeur'
      preLoaderRoute: typeof VoilagesGrandeLargeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voilages/motifs': {
      id: '/voilages/motifs'
      path: '/voilages/motifs'
      fullPath: '/voilages/motifs'
      preLoaderRoute: typeof VoilagesMotifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voilages/rail': {
      id: '/voilages/rail'
      path: '/voilages/rail'
      fullPath: '/voilages/rail'
      preLoaderRoute: typeof VoilagesRailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voilages/unis': {
      id: '/voilages/unis'
      path: '/voilages/unis'
      fullPath: '/voilages/unis'
      preLoaderRoute: typeof VoilagesUnisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  EmbrassesRoute: EmbrassesRoute,
  FaqRoute: FaqRoute,
  FavorisRoute: FavorisRoute,
  GuideDesMesuresRoute: GuideDesMesuresRoute,
  InspirationsRoute: InspirationsRoute,
  LivraisonEtRetoursRoute: LivraisonEtRetoursRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  NouveautesRoute: NouveautesRoute,
  PanierRoute: PanierRoute,
  ProfessionnelsRoute: ProfessionnelsRoute,
  PromotionsRoute: PromotionsRoute,
  RechercheRoute: RechercheRoute,
  SuiviCommandeRoute: SuiviCommandeRoute,
  SurMesureRoute: SurMesureRoute,
  TringlesRoute: TringlesRoute,
  AccessoiresEmbrassesRoute: AccessoiresEmbrassesRoute,
  AccessoiresPetitesPiecesRoute: AccessoiresPetitesPiecesRoute,
  AccessoiresRailsRoute: AccessoiresRailsRoute,
  AccessoiresTringlesRoute: AccessoiresTringlesRoute,
  CommandeConfirmationRoute: CommandeConfirmationRoute,
  CoussinsLinRoute: CoussinsLinRoute,
  CoussinsLotsRoute: CoussinsLotsRoute,
  CoussinsVeloursRoute: CoussinsVeloursRoute,
  GalettesDeChaiseCarreesRoute: GalettesDeChaiseCarreesRoute,
  GalettesDeChaiseRondesRoute: GalettesDeChaiseRondesRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  RideauxLinRoute: RideauxLinRoute,
  RideauxOccultantsRoute: RideauxOccultantsRoute,
  RideauxOeilletsRoute: RideauxOeilletsRoute,
  RideauxPacksRoute: RideauxPacksRoute,
  RideauxRailRoute: RideauxRailRoute,
  RideauxSatinRoute: RideauxSatinRoute,
  RideauxTamisantsRoute: RideauxTamisantsRoute,
  RideauxThermiquesRoute: RideauxThermiquesRoute,
  RideauxVeloursRoute: RideauxVeloursRoute,
  StoresBambouRoute: StoresBambouRoute,
  StoresEnrouleursRoute: StoresEnrouleursRoute,
  StoresJourNuitRoute: StoresJourNuitRoute,
  StoresOccultantsRoute: StoresOccultantsRoute,
  StoresSansPercageRoute: StoresSansPercageRoute,
  VoilagesGrandeLargeurRoute: VoilagesGrandeLargeurRoute,
  VoilagesMotifsRoute: VoilagesMotifsRoute,
  VoilagesRailRoute: VoilagesRailRoute,
  VoilagesUnisRoute: VoilagesUnisRoute,
  AccessoiresIndexRoute: AccessoiresIndexRoute,
  CommandeIndexRoute: CommandeIndexRoute,
  CoussinsIndexRoute: CoussinsIndexRoute,
  GalettesDeChaiseIndexRoute: GalettesDeChaiseIndexRoute,
  RideauxIndexRoute: RideauxIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  VoilagesIndexRoute: VoilagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
